#Project Name
spring.application.name=Smart Expenses Manager


#Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


#Hibernate And JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#Port Number
server.port=${PORT_NUMBER}


# Email Sender configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_ADDRESS}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


#JWT Secret Key
jwt.secret.key=dGhpc0lzQVNlY3VyZTEyMzQ1Njc4OTAxMgnkjlnsakR


#JWT Expiration Time
jwt.expiration.time=3600000
